realsense2_camera_node:
  ros__parameters:
    camera_name: ""
    base_frame_id: "camera_link"
    depth_frame_id: "camera_depth_frame"
    publish_tf: true
    depth_optical_frame_id: "camera_depth_optical_frame"
    color_frame_id: "camera_color_frame"
    color_optical_frame_id: "camera_color_optical_frame"
    infra1_frame_id: "camera_infra1_frame"
    infra1_optical_frame_id: "camera_infra1_optical_frame"
    infra2_frame_id: "camera_infra2_frame"
    infra2_optical_frame_id: "camera_infra2_optical_frame"
